import {ReactNode} from 'react'

export type Quote = {
	line: string|ReactNode
	answers: Array<string>
}

export const sprueche = [
	["Das Reh springt hoch, das Reh springt weit, warum auch nicht, es hat ja Zeit!", ['Das wusste ich nicht']],
	["Der Glatzkopf der die Glatze föhnt, hat mit dem Schicksal sich versöhnt.", ['Das wusste ich nicht']],
	["Der See lädt ein zum Bade... ausgetrocknet... Schade.", ['Das wusste ich nicht']],
	["Verweile nicht in der Vergangenheit, träume nicht von der Zukunft. Konzentriere dich auf den gegenwärtigen Moment.", ['Soso']],
	["Wir denken selten an das, was wir haben, aber immer an das, was uns fehlt.", ['Aha']],
	["Du siehst die Welt nicht so wie sie ist, du siehst die Welt so wie du bist.", ['Verstehe']],
	["Alle Menschen, die man lange im Vorzimmer seiner Gunst stehen läßt, geraten in Gärung oder werden sauer.", ['Aha']],
	// ["Der Philosoph glaubt, der Wert seiner Philosophie liege im Ganzen, im Bau: die Nachwelt findet ihn im Stein, mit dem er baute und mit dem, von da an, noch oft und besser gebaut wird: also darin, daß jener Bau zerstört werden kann und doch noch als Material Wert hat.", ['Aha']],
	["Wo ich Lebendiges fand, da fand ich Willen zur Macht; und noch im Willen des Dienenden fand ich den Willen, Herr zu sein.", ['Aha']],
	// "Was du mir sagst, das vergesse ich. Was du mir zeigst, daran erinnere ich mich. Was du mich tun lässt, das verstehe ich.", ['Aha']],
	// "Wo ist das verdammte Geld, Lebowski ? Wo ist das verdammte Geld, du Drecksack?", ['Aha']],
	["Ohne Handeln sind die besten Absichten in der Welt nichts weiter als das: Absichten.", ['Verstehe']],
	["Die einzige Sache, die zwischen dir und deinem Ziel steht, sind die Bullshit Ausreden, die du dir ständig selbst erzählst.", ['Aha']],
	// "Die Tatsache, dass auf Euren Waffen klar und deutlich 'Replica' steht, und auf meiner 'Desert Eagle 0,50' sollte euch zu denken geben.", ['Aha']],
	// ["Gerne der Zeiten gedenk' ich, da alle Glieder gelenkig - bis auf eins. Doch die Zeiten sind vorüber, steif geworden alle Glieder - bis auf eins.", ['Aha']],
	["Weisheit stellt sich nicht immer mit dem Alter ein. Manchmal kommt auch das Alter ganz allein.", ['Aha']],
	["Geliebt wirst du einzig, wo du schwach dich zeigen darfst, ohne Stärke zu provozieren.", ['Aha']],
	// ["Stärke wächst nicht aus körperlicher Kraft - vielmehr aus unbeugsamem Willen.", ['Aha']],
	["Man will nicht nur glücklich sein, sondern glücklicher als die anderen. Und das ist deshalb so schwer, weil wir die anderen für glücklicher halten, als sie sind.", ['Verstehe']],
	["Mut ist, wenn man Todesangst hat, aber sich trotzdem in den Sattel schwingt.", ['Sieh\' an']],
	// "Die Frau kontrolliert ihren Sex, weil sie für Sex all das bekommt, was ihr noch wichtiger ist als Sex.", ['Aha']],
	["Wer lachen kann, dort wo er hätte heulen können, bekommt wieder Lust zu Leben.", ['Aha']],
	// "Eigentlich wollte ich dir schenken eine Torte. Doch ich kann leider nicht backen. Darum gibt es nur nette Worte.", ['Aha']],
	["Vertrauen ist wie Papier. Einmal zerknüllt, wird es nie wieder perfekt.", ['Aha']],
	["Folge deinem Herzen, aber nimm dein Hirn mit.", ['Aha']],
	["Sobald du anfängst, dir Gedanken darüber zu machen, was andere über dich denken, hörst du auf, du selbst zu sein.", ['Verstehe']],
	// '"Wie trinkst du deinen Kaffee?" "Müde."',
	["Bist du traurig, hast du Sorgen, soll ich dir mein Lächeln borgen? Nutz es gut, es bringt dir Glück und wenn du`s nicht mehr brauchst, gib`s mir irgendwann zurück.", ['Aha']],
	// ["Wer will findet Wege, wer nicht will, findet Gründe.", ['Aha']],
	["Alle sagten: Das geht nicht. Dann kam einer, der wusste das nicht und hat's gemacht.", ['Aha']],
	["Manche Menschen wollen immer nur glänzen, obwohl sie keinen Schimmer haben.", ['Aha']],
	// ["Das erste, was man bei einer Abmagerungskur verliert, ist die gute Laune.", ['Aha']],
	// "Bei manchen Menschen geht alles schnell zum einen Ohr rein und zum anderen raus - die haben auch nicht viel dazwischen.", ['Aha']],
	["Das Lernen macht stets dann Verdruß’, wenn man’s nicht will, es aber muß.", ['Verstehe']],
	// "Ich brauche nur Fettgedrucktes zu lesen, schon nehme ich zu.", ['Aha']],
	["Paradox ist, wenn einer sich im Handumdrehen den Fuß bricht.", ['Verstehe']],
	// "Liebschaften sind wie Pilzgerichte, ob sie ungefährlich waren, weiß man erst später.", ['Aha']],
	// ["Pessimisten sind Leute, die mit der Sonnenbrille in die Zukunft schauen.", ['Aha']],
	// "Der schläft gut, der nicht weiß, wie schlecht er schläft.", ['Aha']],
	// ["Will jemand eine Jungfrau frein, darf er nicht penibel sein.", ['Aha']],
	// "Was du liebst, lass frei. Kommt es zurück, gehört es dir - für immer.", ['Aha']],
	["Fordere viel von dir selbst und erwarte wenig von anderen. So wird dir viel Ärger erspart bleiben.", ['Aha']],
	["Sage es mir, und ich vergesse es. Zeige es mir, und ich erinnere mich. Lass es mich tun, und ich behalte es.", ['Verstehe']],
	["Falls du glaubst, dass du zu klein bist, um etwas zu bewirken, dann versuche mal zu schlafen, wenn eine Mücke im Raum ist.", ['Verstehe']],
	["In der Wut und in der Liebe verliert der Mensch seine Intelligenz.", ['Aha']],
	["Denke daran, dass etwas, was du nicht bekommst, manchmal eine wunderbare Fügung des Schicksals sein kann.", ['Aha']],
	["Denke daran, dass Schweigen manchmal die beste Antwort ist.", ['Aha']],
	// ["Jede schwierige Situation, die du jetzt meisterst, bleibt dir in der Zukunft erspart.", ['Aha']],
	["Lasse das Verhalten anderer nicht deinen inneren Frieden stören.", ['Aha']],
	// "Die Ironie will es so, dass wir dann, wenn wir das Objekt unserer Wünsche erlangt haben, immer noch nicht zufrieden sind. Auf diese Weise nimmt die Begierde nie ein Ende und ist eine ständige Quelle der Schwierigkeiten. Das einzige Gegenmittel ist die Genügsamkeit.", ['Aha']],
	// ["Wir leben nicht, um zu glauben, sondern um zu lernen.", ['Aha']],
	// "Besuche einmal im Jahr einen Ort, den du noch nicht kennst.", ['Aha']],
	// "Die Übung in Geduld bewahrt uns vor dem Verlust unserer Gelassenheit. Dadurch haben wir die Möglichkeit unser Urteilsvermögen zu trainieren, selbst in sehr schwierigen Situationen. Es gibt uns inneren Raum. Und durch diesen Raum gewinnen wir ein gewisses Maß an Selbstbeherrschung, welche uns erlaubt auf Situationen in angemessener Weise reagieren zu können. Mitfühlend, anstatt durch unsere Wut und Verärgerung getrieben.", ['Aha']],
	["Ziele erreichen ist wie Bergsteigen. Es zieht anfangs Energie und gibt sie dann um ein Vielfaches zurück.", ['Aha']],
	["Fokus ist die ausnahmslose Bündelung der Kräfte auf eine Sache.", ['Verstehe']],
	// "Menschen bewegen sich, sobald Licht, Hitze und Timing im Einklang sind.", ['Aha']],
	// "Jeder Abend ist die letzte Chance, jeder Morgen ein neuer Anfang.", ['Aha']],
	// ["Ist etwas zerronnen, ist es aus anderer Sicht vielleicht gewonnen.", ['Aha']],
	["Ein Vorurteil wird immer nur ein Teil vom Ganzen sein.", ['Aha']],
	["Wenn du kritisiert wirst, dann musst du irgend etwas richtig machen. Denn man greift nur denjenigen an, der den Ball hat.", ['Verstehe']],
	["Besser langsam und richtig als schnell und falsch.", ['Verstehe']],
	// ["Ich fürchte nicht den Mann, der 10.000 Kicks einmal geübt hat, aber ich fürchte mich vor dem, der einen Kick 10.000 mal geübt hat.", ['Aha']],
	["Der Wille gestaltet den Menschen, zum Erfolg braucht der jedoch Mut und Ausdauer.", ['Verstehe']],
	["Eine wahrhafte Anstrengung in die Richtung eines bestimmten Zieles, gibt dem Leben Sinn und Zweck.", ['Verstehe']],
	["Am meisten über einen Menschen sagt nicht aus, wie er mit Freunden umgeht, sondern mit Fremden.", ['Aha']],
	["Geh deinen Weg und lass die Leute reden!", ['Aha']],
	// "Des is wia bei jeda Wissenschaft, am Schluss stellt sich dann heraus, dass alles ganz anders war.", ['Aha']],
	["Jedes Ding hat drei Seiten, eine positive, eine negative und eine komische.", ['Verstehe']],
	// "Als ich das Licht der Welt und sodann die Hebamme erblickte, war ich sprachlos. Ich hatte diese Frau ja noch nie in meinem Leben gesehen.", ['Aha']],
	["Kunst ist schön, macht aber viel Arbeit.", ['Aha']],
	["Wir sind so gerne in der freien Natur, weil diese keine Meinung über uns hat.", ['Aha']],
	["Die Hoffnung ist der Regenbogen über den herabstürzenden Bach des Lebens.", ['Aha']],
	// ["Überzeugungen sind gefährlichere Feinde der Wahrheit als Lügen.", ['Aha']],
	["Wenn man ein Wozu des Lebens hat, erträgt man jedes Wie.", ['Aha']],
	// ["Hast du eine große Freude an etwas gehabt, so nimm Abschied! Nie kommt es zum zweiten Male.", ['Aha']],
	// ["Toleranz ist ein Beweis des Mißtrauens gegen ein eigenes Ideal.", ['Aha']],
	["Es ist leichter, einer Begierde ganz zu entsagen, als in ihr maßzuhalten.", ['Aha']],
	["Viele sind hartnäckig in Bezug auf den einmal eingeschlagenen Weg, wenige in Bezug auf das Ziel.", ['Aha']],
	["Dem wird befohlen, der sich nicht selbst gehorchen kann.", ['Aha']],
	["Wünschen ist ein Anzeichen von Genesung oder Besserung.", ['Aha']],
	["Die Wissenschaft nötigt uns, den Glauben an einfache Kausalitäten aufzugeben.", ['Aha']],
	["Wenn du lange in einen Abgrund blickst, blickt der Abgrund auch in dich hinein.", ['Aha']],
	["Niemand rettet uns, außer wir selbst. Niemand kann und niemand darf das. Du musst selbst den Weg gehen.", ['Aha']],
	["Zuerst wird man für dumm gehalten. Dann ist man ein Lügner.", ['Verstehe']],
	["That's life (That's life), that's life and I can't deny it; Many times I thought of cutting out but my heart won't buy it; But if there's nothing shaking come this here July; I'm gonna roll myself up in a big ball and die; My, my", ['Alright']],
	["Wer etwas ändern will, sollte wissen wo er steht.", ['Aha']],
	["1% sind besser als gar nichts.", ['Aha']],
	// ["Komplimente sind wie ungedeckte Schecks. Will man sie einlösen, platzen sie.", ['Aha']],
	// ['Altruistische Verhaltensweisen wurden – mit Hilfe der jeweils gewählten Begriffsdefinition bzw. erdachten Interpretation – bei Menschen und verschiedenen Tierarten „nachgewiesen“;[7][3] eine 2009 publizierte Studie schreibt Altruismus auch Pflanzen zu,[8] und 2010 wurde in der Zeitschrift Nature altruistisches Verhalten bei Bakterien beschrieben.[9]', ['Aha']],
	["Eine Seefahrt unterscheidet sich von einer schönen Seefahrt dadurch, dass man der einen ihr baldiges Ende herbeiwünscht und der anderen, dass sie nicht enden möge.", ['Aha']],
	// "First you are taken for a fool. Then you are a liar.", ['Aha']],
	// "Man kann nur die Dinge tun, die man selber will.", ['Aha']],
	["The imperfection of the present is the opportunity for the future.", ['I see']],
	["It's possibly good, if people listen to you, to sometimes talk crap so that people always verify what you're saying.", ['I see']],
	// ["Für ein Genie ist es Alltag, missverstanden zu werden.", ['Aha']],
	// ["Das Schönste, was wir erleben können, ist das Geheimnisvolle. Es ist das Grundgefühl, das an der Wiege von wahrer Kunst und Wissenschaft steht. Wer es nicht kennt und sich nicht mehr wundern, nicht mehr staunen kann, der ist sozusagen tot und sein Auge erloschen. Das Erlebnis des Geheimnisvollen - wenn auch mit Furcht gemischt- hat auch die Religion gezeugt.", ['Aha']],
	["Wer viel Freude hat, muss ein guter Mensch sein: aber vielleicht ist er nicht der Klügste, obwohl er gerade das erreicht, was der Klügste mit all seiner Klugheit erstrebt.", ['Aha']],
	["Ein Kerl, der spekuliert, ist wie ein Tier auf dürrer Heide. Von bösem Geist im Kreis herumgeführt und ringsumher ist schöne, grüne Weide.", ['Ach Goethe...']],
	["Man kann sich entscheiden, glücklich zu sein.", ['Achwas']],
	["Denke nicht so oft an das, was dir fehlt, sondern an das, was du hast.", ['Aha']],
	["Schöne Worte sind nicht immer wahr. Wahre Worte sind nicht immer schön.", ['Verstehe']],
	["Die meisten Menschen wollen lieber durch Lob ruiniert als durch Kritik gerettet werden.", ['Könnte sein']],
	["Jetzt sind die guten alten Zeiten, nach denen wir uns in zehn Jahren zurücksehnen.", ['Aha']],
	["Ein Kompromiss ist perfekt, wenn alle Seiten unzufrieden sind.", ['Aha']],
	["Sarkasmus springt ein, wenn man müde ist, wütend zu sein.", ['Aha']],
	["Alles, was wert ist erreicht zu werden, kostet Mühe.", ['Aha']],
	["Du bist nicht gut, weil du auffällst. Du bist gut, wenn auffällt, dass du fehlst.", ['Verstehe']],
	["Die Welt ist starr oder beweglich, je nachdem, wie stark man sich fühlt.", ['Aha']],
	["Der Preis spielt keine Rolle, wenn man etwas wirklich will.", ['Aha']],
	["Im Leben muss man einiges einstecken, wofür man gar keine Tasche hat.", ['Verstehe']],
	["Der Mensch, der den Berg abtrug, war derselbe, der anfing, kleine Steine wegzutragen.", ['Aha']],
	["Bald hast du keine Zähne mehr zum Beißen, drum musst auf alles und jeden du scheißen.", ['Oh-kay']],
	["Alle guten Dinge haben etwas Lässiges und liegen wie Kühe auf der Wiese.", ['Aha']],
	["Neid ist die höchste Form der Anerkennung.", ['Aha']],
	["Wer kämpft, kann verlieren, wer nicht kämpft hat schon verloren.", ['Aha']],
	["Jeder kehre vor der eigenen Tür und die Welt ist sauber.", ['Aha']],
	["Wie alt man geworden ist, sieht man an den Gesichtern derer, die man jung gekannt hat.", ['Aha']],
	["Das Glück besteht nicht darin, dass du tun kannst, was du willst, sondern darin, dass du immer willst, was du tust.", ['Aha']],
	["Zeit mag Wunden heilen, aber sie ist eine miserable Kosmetikerin.", ['Aha']],
	["Klug sein besteht zur Hälfte darin, zu wissen, was man nicht weiß.", ['Aha']],
	["Nichts ist entspannender, als anzunehmen, was kommt.", ['Aha']],
	["Versuche zu kriegen, was du liebst. Ansonsten musst du lieben, was du kriegst.", ['Verstehe']],
	["Bei der falschen Person kannst du nichts richtig machen. Bei der richtigen Person kannst du nichts falsch machen.", ['Aha']],
	["Der liebt nicht, der die Fehler des Geliebten nicht für Tugenden hält.", ['Aha']],
	["Für die Welt, bist du irgendjemand, aber für irgendjemand bist du die Welt.", ['Aha']],
	["Liebe und Hass sind nicht blind, aber sie sind geblendet von dem Feuer, das sie selbst mit sich tragen.", ['Aha']],
	["Liebe mich dann, wenn ich es am wenigsten verdient habe, denn dann brauche ich es am meisten.", ['Aha']],
	["Mancher findet sein Herz nicht eher, als bis er seinen Kopf verliert.", ['Aha']],
	// ["Heirate doch einen Archäologen. Je älter du wirst, desto interessanter findet er dich.", ['Aha']],
	// ["Nicht durch Worte, aber durch Handlungen zeigt sich wahre Treue und wahre Liebe.", ['Aha']],
	["When people start being themselves they offer something no one else can give.", ['Alright']],
	// ["Optimismus für Singles: Mein Bett ist halb voll.", ['Aha']],
	["Im Alter kommt keine Gelassenheit. Man schafft es nur nicht mehr, bis an die Decke zu gehen.", ['Verstehe']],
	["Wenn du eh in den Seilen hängst, kannst du auch erstmal Schaukeln.", ['Hui']],
	["Ich bin nicht gestresst und genervt. Es ist nur einfach nicht die beste Zeit, um mir eine Kettensäge anzuvertrauen.", ['Aha']],
	["Wer zuletzt lacht hat es nicht eher verstanden.", ['Achso']],
	["Lieber locker vom Hocker, als hektisch über'n Ecktisch!", ['Aha']],
	["Jedenfalls ist es besser, ein eckiges Etwas zu sein als ein rundes Nichts.", ['Oh-kay']],
	["Lass dir von keinem Fachmann imponieren, der dir erzählt: 'Lieber Freund, das mache ich schon seit zwanzig Jahren so!' Man kann eine Sache auch zwanzig Jahre lang falsch machen.", ['Aha']],
	["Du kannst den Hahn zwar einsperren, aber die Sonne geht dennoch auf.", ['Mal testen..']],
	["Life is 10% what happens to us and 90% how we react to it.", ['I see']],
	["There is no greater fool than he who thinks himself wise; no one wiser than he who suspects he is a fool.", ['I see']],
	["Focussing is not about saying \"yes\", it's about saying \"No\".", ['Alright']],
	["Du bist hervorgegangen als erfolgreiches Konzept milliarden Jahre andauernder Überlebenskämpfe.", ['Aha']],
	["Eine wahre Aussage wird nicht wahrer, wenn ein hohes Tier sie spricht.", ['Aha']],
	["Betrachte jeden Moment, als hättest du ihn nicht selbst geschaffen, sondern als wäre er dir zugeteilt, zur Verfügung gestellt.", ['Hmm']],
	["But, oh, I'm just a soul whose intentions are good. Oh, Lord, please, don't let me be misunderstood.", ['Nice']],
	["Sei nett zu Programmierern: Verstecke keine Nadeln in Heuhaufen!", ['Ich werde vorsichtig sein']],
	// ["\"Wir könnten uns ein Fernglas kaufen.\" \"Und dann?\" \"Dann sehn wir weiter.\"", ['Sehr witzig']],
	["Ruhig Blut: Immer ein Tag nach dem anderen.", ['Alles klar']],
	["There's no improvement without challenge.", ['Ok']],
	// ["\"Die Welt verbessern\" - Fang am besten gleich mit deiner an!", ['Aha']],
	// ["Die Welt ist ungerecht! Sowie das Leben.", ['Aha']],
	["Anzunehmen, dass man dumm ist, ist klüger, als vorauszusetzen, dass man klug ist.", ['Achso']],
	["Der Weise wählt, was er sich nicht aussuchen kann.", ['Achso']],
	['Oft gibt es ein Interesse, wo man gar keines vermutet.', ['Verstehe']],
	['You do - you find out. You try - you’ll never know.', ['Oh..kay']],
	['If you\'re overthinking, write. If your mind is blank, read.', ['Alright']],
	['Manchmal ist die Frage angebracht, ob man sich das zumuten will...', ['Soso']],
	['The effort does not justify the goal - The goal justifies the effort.', ['Well well']],
	['Ist dein Kopf leer: lies! Ist dein Kopf voll: schreib!', ['Achne']],
	['Jeder sucht zu vermeiden, was die eigene Identität bedroht.', ['Achwas']],
	['Arbeit ist auch dann Arbeit, wenn sie nicht bezahlt wird', ['Soso']],
	['Wie man sich entscheiden kann, glücklich zu sein, kann man sich auch entscheiden, stark zu sein.', ['Achwas']],
	['Nutze die Gunst der Stunde, nicht die Gelegenheit.', ['Alles klar']],
	// [<>Der Mensch ist nichts Besond'res<br />besonders ist sein Werk<br />Wie Gottes Werk besonders<br />ist Gott an sich ein Zwerg</>, ['Nicht wahr']],
	['Wenn man nach dem Weg sucht, ist es hilfreich zu wissen, wo man sich befindet.', ['Achne']],
	['Tue was sinnvoll, nicht was vorteilhaft ist.', ['Werd\'s versuchen']],
	['Das Alter ist eine Zeit, in der man das Glück zurückgibt, das einem geschenkt wurde.', ['Das ist neu']],
	['Being less annoyed is better than being more happy.', ['Really']],
	['I\'ll tell you a secret. Something they don\'t teach you in your temple. The Gods envy us. They envy us because we\'re mortal, because any moment might be our last. Everything is more beautiful because we\'re doomed. You will never be lovelier than you are now. We will never be here again.', ['Oh well']],
	[['Wer Ausnahmen macht, hat Regeln.'], ['Logisch']],
	[[<>Man <i>muss</i> gar nichts tun. Nicht mal, drüber nachdenken.</>], ['']],
	['Es gibt manchmal so ungeschriebene Gesetze im eigenen Leben, von denen man gar nichts weiß.', ['Nie gehört']],
	['Tech Music is not about feelings but the cultural foundations of our being. The fires we danced around to the drums in ancient times to chase animal away.', ['Never heard']],
	['Räum\' deinen Kopf auf und es wird besser!', ['I\'ll try']],
	['Wenn Kritik stimmt, trifft sie. Meist setzt das einen Umwandlungsprozess in Gang.', ['Na schön']],
	['Etwas ist immer zu allem ein Puzzlestück.', ['Na schön']],
	['Bei der Frage, \'was würde man am liebsten tun\', denkt man selten an die Zukunft.', ['Kommt vor...']],
	// ['Ich kann ertragen, wenn ich schuldig werde. Ich kann aber nicht ertragen, wenn andere schuldig werden.', ['Kommt vor...']],
	[<>'Es ist besser, daran zu denken, was alles <i>nicht</i> passieren könnte.'</>, ['Äh...']],
	// ['Es gibt kein höheres Ziel, als Anführer einer Sippe sein zu wollen, denn das, was man in der Welt entwickelt sehen will, muss man zuerst bei sich selbst entwickeln. Und das lohnt sich in jedem Fall.', ['']]
	// ['Man muss irgendwo attraktiv und sich seiner Attraktivität bewusst sein.', ['Aha']],
	// ['Die klügsten Leute unterhalten sich darüber, wer am klügsten ist, die Schönsten Leute unterhalten sich darüber, wer am schönsten ist und die coolsten Leute unterhalten sich darüber, wer am coolsten ist.', ['Echt jetzt?']],
	['Sit down, please! Drink a little coffee.', ['Alright']],
	['Man kann nicht nachempfinden, ob jemand Respekt verdient.', ['Aha']],
	['Der Gewinn für die Menschheit steht über allem.', ['Aha']],
	['Blutige Nase muss sein!', ['Aua!']],
	// ['Die unterschwelligen Gedanken, die, die man fast nicht hört, sind die, die einen bewegen.', ['']],
	['Lang ist\'s her!', ['Stimmt']],
	// ['Im Leben muss man über vieles hinwegsehen, für das man gar nicht groß genug ist.', ['Aha']],
	['Sich überlegen zu fühlen, ist nah an der reinen Freude', ['Soso']],
	['When all is done, there\'s only party. Party Planet.', ['That would be great!']],
	['Am Anfang sucht man einen Anfang.', ['Ach ne']],
	['Großes baut man aus Kleinem.', ['Ach was']],
	['I did what I did and some went well.', ['Very well then.']],
	['Man sollte so arbeiten können, als würde man es umsonst tun.', ['Hmm']],
	['Verrückte sind Training für die Gemeinschaft.', ['Achso']],
]



export const quotes:Array<Quote> = sprueche.map(s => {
	return {line: s[0], answers: s[1]} as Quote
})