
export const routes: {[key: string]: [route: string, title: string]} = {
	about: ['/about', 'Über Digi Craft'],
	achievements: ['/achievements', 'Erfolge'],
	bodycraft: ['/bodycraft', "Body Craft"],
	components: ['/components', 'Components'],
	decider: ['/decider', 'Der Entscheider'],
	dev: ['/dev', 'Development Page'],
	digicraft: ['/digicraft', 'Digi Craft'],
	imprint: ['/meta/imprint', 'Impressum'],
	jobs: ['/jobs', 'Jobs'],
	mentalAidKit: ['/mental-aid-kit', 'Mental Aid Kit'],
	music: ['/music', 'Technoscout Music'],
	neoCortex: ['/neoCortex', 'Neo Cortex Collection'],
	news: ['/news', 'News'],
	notationTrainer: ['/apps/notationTrainer', 'Schach-Notationstrainer'],
	numberGuessing: ['/numberGuessing', 'Zahlenraten Reloaded'],
	passMaker: ['/passMaker', 'Pass Maker'],
	privacy: ['/privacy', 'Datenschutz'],
	radio: ['/radio', 'Digi Radio'],
	settings: ['/meta/settings', 'Einstellungen'],
	svgEditor: ['/svg-editor', 'Coder\'s SVG Editor'],
	sourceCode: ['/sourceCode', 'Source Code'],
	worktime: ['/worktime', 'Arbeitszeit'],
}
