
export const routes: {[key: string]: [route: string, title: string]} = {
	about: ['/about', 'Über Digi Craft'],
	achievements: ['/apps/achievements', 'Erfolge'],
	decider: ['/decider', 'Der Entscheider'],
	digiCraft: ['/', ''],
	imprint: ['/meta/imprint', 'Impressum'],
	music: ['/music', 'Technoscout Music'],
	neoCortex: ['/neoCortex', 'Neo Cortex Collection'],
	news: ['/news', 'News'],
	notationTrainer: ['/apps/notationTrainer', 'Schach-Notationstrainer'],
	numberGuessing: ['/numberGuessing', 'Zahlenraten Reloaded'],
	passMaker: ['/passMaker', 'Pass Maker'],
	privacy: ['/privacy', 'Datenschutz'],
	radio: ['/radio', 'Digi Radio'],
	settings: ['/meta/settings', 'Einstellungen'],
	svgEditor: ['/dev', 'Coder\'s SVG Editor'],
	sourceCode: ['/sourceCode', 'Source Code'],
	worktime: ['/worktime', 'Arbeitszeit'],
}
